version: '3.9'

services:
  api:
    container_name: api-sv
    image: node-app
    build: .
    restart: always
    env_file: ./.env.dev
    ports:
      - "5000:5000"
    links:
      - mongodb
      - mysql
    networks:
      - mongodb_network
      - mysql_network

  mongodb:
    container_name: mongodb-sv
    hostname: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
      # - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - mongodb-data:/data/db/
    networks:
      - mongodb_network

  mysql:
    container_name: mysql-sv
    hostname: mysql
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql_network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - mysql_network

  postgres:
    container_name: postgres-sv
    hostname: mysql
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  my-db:
    driver: local
    name: my-data
  mongodb-data:
    driver: local
    name: mongo-data
  postgres-data:
    driver: local
    name: postgres-data

networks:
  mongodb_network:
    driver: bridge
    name: mongo-network
  mysql_network:
    driver: bridge
    name: mysql-network
  postgres_network:
    driver: bridge
    name: postgres-network